Todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todo/", include("todo.urls")),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from todo.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskComplete,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

app_name = "todo"

urlpatterns = [
    path("task/", TaskListView.as_view(), name="task-list"),
    path("task_create/", TaskCreateView.as_view(), name="task-create"),
    path("task_update/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("task_delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("task_complete/<int:pk>/", TaskComplete.as_view(), name="task-complete"),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags_create/", TagCreateView.as_view(), name="tag-create"),
    path("tags_update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags_delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
]

todo/models.py
from django.db import models


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", blank=True, related_name="tags")

    class Meta:
        ordering = ["completed", "-created_at"]

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from todo.models import Task, Tag


class TaskCreateForm(forms.ModelForm):
    deadline = forms.DateField(
        widget=forms.DateInput(
            attrs={"type": "date"}
        ),
        required=False
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Task
        fields = ['content', 'deadline', 'tags']

todo/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.shortcuts import redirect

from todo.forms import TaskCreateForm
from todo.models import Task, Tag
from django.urls import reverse_lazy


class TaskListView(ListView):
    model = Task
    template_name = "task_list.html"
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(UpdateView):
    form_class = TaskCreateForm
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TaskComplete(View):
    model = Task

    def post(self, request, pk, *args, **kwargs):
        task = self.model.objects.get(id=pk)
        task.completed = not task.completed
        task.save()
        return redirect("todo:task-list")


class TagListView(ListView):
    model = Tag
    template_name = "tag_list.html"
    ordering = ["name"]


class TagCreateView(CreateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(UpdateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <title>Todo list</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin="anonymous">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}  
  
</head>
<body>
  <div class="container-fluid" style="margin-top: 20px">
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-10 ">

        {% block content %}
        {% endblock %}

      </div>
    </div>
  </div>
</body>
</html>

templates/includes/sidebar.html
<ul class="toggle-nav-sidebar sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Tasks</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure that you want to delete this task({{ tag.name }})?</h1>
  <p><i>All related data will be also delete!!!</i></p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
  
    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary btn-success">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
      Add tag
    </a>
  </h1>
  
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              <strong>{{ tag.name }}</strong>
          </td>
          <td>
              <a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo:tag-delete' pk=tag.id %}"  class="btn btn-danger">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags yet.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure that you want to delete this task({{ task.content }})?</h1>
  <p><i>All related data will be also delete!!!</i></p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} new task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
  
    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary btn-success">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <header class="inline-group">
    <h1 style="display: inline;">Tasks todo</h1>
    <a href="{% url 'todo:task-create' %}"
       class="btn btn-success"
       style="display: inline;">Add task</a>
  </header>
  
  {% if task_list %}
    <ol style="margin-top: 10px">
      {% for task in task_list %}
        <li>
          <h5 style="display: inline;">{{ task.content }}</h5>
            
            <form action="{% url 'todo:task-complete' pk=task.id %}" method="post">
              {% csrf_token %}
              {{ form.as_p }}
              {% if task.completed %}
                <p style="display: inline; color: green">Done</p>
                <button type="submit" class="btn btn-secondary">
                  Undo
                </button>
              {% else %}
                <p style="display: inline; color: red">In progress</p>
                <button type="submit" class="btn btn-success link-to-page">
                  Complete
                </button>
              {% endif %}
            </form>
          <ul>
            <li>
              <p>Created at: {{ task.created_at }}</p>
              {% if task.deadline %}
                <p style="color: red"> DEADLINE: {{ task.deadline }}</p>
              {% endif %}
            </li>
            <li>
              <p><strong>Tags:</strong></p>
              {% for tag in task.tags.all %}
                <p><i>#{{ tag.name }}</i></p>
              {% endfor %}
            </li>
          </ul>
          <a href="{% url 'todo:task-delete' pk=task.id %}" class="btn btn-danger form-inline">Delete</a>
          <a href="{% url 'todo:task-update' pk=task.id %}" class="btn btn-secondary form-inline">Update</a>
        </li>
        <hr>
      {% endfor %}
    </ol>
  {% else %}
    <p>You haven't created any task yet</p>
  {% endif %}
    
      
{% endblock %}